services:
  - type: web
    name: crm-backend
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn crm_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crm_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: crm-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "crm-backend.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://leadsfrontend.vercel.app,http://localhost:5173"

  - type: worker
    name: crm-celery-worker
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "celery -A crm_backend worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crm_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: crm-redis
          property: connectionString
      - key: SECRET_KEY
        fromService:
          type: web
          name: crm-backend
          property: env.SECRET_KEY

  - type: worker
    name: crm-celery-beat
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "celery -A crm_backend beat --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crm_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: crm-redis
          property: connectionString
      - key: SECRET_KEY
        fromService:
          type: web
          name: crm-backend
          property: env.SECRET_KEY

  - type: redis
    name: crm-redis
    region: oregon
    plan: free

  - type: postgres
    name: crm_db
    region: oregon
    plan: free
